---
- hosts: all
  become: yes
  remote_user: vagrant
  gather_facts: no
  pre_tasks:

    - name: 'Atualizando o repo'
      raw: 'yum update'
    - name: 'Instalando Pyhton'
      raw: 'yum install -y python'
    - name: 'Instalando Pyhton3'
      raw: 'yum install -y python3'

  roles:
    - { role: install-docker, tags: ["install_docker_role"] }   
